### ISSUE TITLE
Crash when trying to download

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#124]
Downloading files from https://material-foundation.github.io/material-theme-builder/#/custom cause s crash
```
java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:null/eab2262e-4086-4ce9-b6a5-001e275dd209
	at android.app.DownloadManager$Request.<init>(DownloadManager.java:452)
	at l2.d.u(Unknown Source:14)
	at l2.d.e(Unknown Source:0)
	at l2.d$a.t(Unknown Source:69)
	at y2.a.k(Unknown Source:11)
	at kotlinx.coroutines.internal.f.k(Unknown Source:66)
	at w2.i.k(Unknown Source:37)
	at o2.v1$a.onClick(Unknown Source:21)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by plateaukao** [comment]
I don't see files to be dowloadable on the website

**Comment by Kita2345** [comment]
above to the right of CUSTOM

**Comment by plateaukao** [comment]
Looks like Android built-in download manager only supports http/https uri:
And the link you provided is trying to download non http/https url.
![image](https://user-images.githubusercontent.com/4084738/171651042-6152088e-4292-47ed-a49c-6421bea12cd5.png)
