### ISSUE TITLE
crash when URL is too long

### ISSUE THREAD

**Issue by Apaaja20** [plateaukao/einkbro#254]
```
java.lang.IllegalArgumentException: Can't represent a size of 272973 in Constraints
	at d2.a$a.a(SourceFile:41)
	at d2.a$a.b(SourceFile)
	at d2.b.a(SourceFile)
	at d2.b.b(SourceFile)
	at a0.m1.a(SourceFile:373)
	at a0.p.c(SourceFile:63)
	at l1.t.b(SourceFile:44)
	at l1.g0.C(SourceFile:9)
	at p0.h$a.a(SourceFile:64)
	at p0.a0.C(SourceFile:7)
	at a0.x2.p0(SourceFile:45)
	at l1.k1.a(SourceFile:75)
	at l1.e0$b.O0(SourceFile:172)
	at l1.e0$b.b(SourceFile:180)
	at c0.w$a.c(SourceFile:38)
	at l1.t.b(SourceFile:44)
	at a0.t2.X(SourceFile:72)
	at j1.u.q(SourceFile:13)
	at l1.z.b(SourceFile:15)
	at a0.n0.q(SourceFile:35)
	at l1.c.q(SourceFile)
	at l1.z.b(SourceFile:15)
	at w0.n0.q(SourceFile:6)
	at l1.z.b(SourceFile:15)
	at t.m1.q(SourceFile:122)
	at l1.z.b(SourceFile:15)
	at t.m1.q(SourceFile:122)
	at l1.z.b(SourceFile:15)
	at l1.g0.C(SourceFile:9)
	at p0.h$a.a(SourceFile:64)
	at p0.a0.C(SourceFile:7)
	at a0.x2.p0(SourceFile:45)
	at l1.k1.a(SourceFile:75)
	at l1.e0$b.O0(SourceFile:172)
	at l1.e0$b.b(SourceFile:180)
	at t.h.c(SourceFile:87)
	at l1.t.b(SourceFile:44)
	at t.s.q(SourceFile:104)
	at l1.z.b(SourceFile:15)
	at l1.g0.C(SourceFile:9)
	at p0.h$a.a(SourceFile:64)
	at p0.a0.C(SourceFile:7)
	at a0.x2.p0(SourceFile:45)
	at l1.k1.a(SourceFile:75)
	at l1.e0$b.O0(SourceFile:172)
	at l1.e0$b.b(SourceFile:180)
	at t.h.c(SourceFile:87)
	at l1.t.b(SourceFile:44)
	at t.a1.q(SourceFile:38)
	at l1.z.b(SourceFile:15)
	at l1.g0.C(SourceFile:9)
	at p0.h$a.a(SourceFile:64)
	at p0.a0.C(SourceFile:7)
	at a0.x2.p0(SourceFile:45)
	at l1.k1.a(SourceFile:75)
	at l1.e0$b.O0(SourceFile:172)
	at l1.k0.c(SourceFile:55)
	at l1.k0.j(SourceFile:131)
	at l1.k0.f(SourceFile:69)
	at androidx.compose.ui.platform.AndroidComposeView.b(SourceFile:14)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:22)
	at android.view.View.draw(View.java:17240)
	at android.view.View.updateDisplayListIfDirty(View.java:16219)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16182)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16182)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16182)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16182)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
	at android.view.View.updateDisplayListIfDirty(View.java:16182)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by plateaukao** [comment]
please follow issue template.
