### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#90]
```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
	at android.app.Activity.startActivityForResult(Activity.java:4590)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4548)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:4909)
	at android.app.Activity.startActivity(Activity.java:4877)
	at k2.d.c(Unknown Source:33)
	at de.baumann.browser.activity.BrowserActivity$h0.a(Unknown Source:27)
	at de.baumann.browser.activity.BrowserActivity$h0.b(Unknown Source:0)
	at d2.d0.b(Unknown Source:3)
	at d2.d0.a(Unknown Source:0)
	at de.baumann.browser.activity.BrowserActivity.F2(Unknown Source:20)
	at de.baumann.browser.activity.BrowserActivity.h0(Unknown Source:0)
	at d2.a0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:6605)
	at android.view.View.performClickInternal(View.java:6582)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25897)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 2108236 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1129)
	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3730)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1671)
	... 25 more
```

**Comment by plateaukao** [comment]
Hi @Kita2345 
Do you have any more information about how this crash happens? (what device you are using, what version of EinkBro you're using, what website you're browsing, what actions you did before it crashes).
Because the App source code is obfuscated in release version, the call stack does not help much.

**Comment by Kita2345** [comment]
https://github.com/plateaukao/browser/issues/87

**Comment by Kita2345** [comment]
URL
https://mars.nasa.gov/participate/send-your-name/mars2020/certificate/599173796266

**Comment by plateaukao** [comment]
no crash now. it will show the url is not supported to download.
